[repository]
name = "hyprXPrimary"
authors = ["Zakk"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "058fef2decc91a0849c7556a0ec428fe45a4d418"],
	["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "ba7378e9bfa6adef1f4d7f7beeec0dbd9826d952"]
]


[hyprXPrimary]
description = "Primary XWayland display"
authors = ["Zakk"]
output = "hyprXPrimary.so"
build = [
	"make all"
]
